### ISSUE TITLE
Would you please kind push 0.132 to your mvn repository?

### ISSUE THREAD

**Issue by netroby** [leibnitz27/cfr#13]
Would you please kind push 0.132 to your mvn repository?
we have an very old project, dependency with your 0.132 , please add it to your mvn repository

**Comment by leibnitz27** [comment]
Pushed.  Should turn up in a few hours.
(note that because it predates my switching to poms, I've hacked things a little, the binary in the release is the original 132 binary).

I'm sure you know this, but there's been significant improvements since 0.132 - it shouldn't be a big deal to upgrade so if you get a chance, I strongly recommend doing that!

**Comment by leibnitz27** [comment]
https://search.maven.org/artifact/org.benf/cfr/0.132/jar

**Comment by netroby** [comment]
Thanks for your great hard works.
