### ISSUE TITLE
More releases

### ISSUE THREAD

**Issue by GraxCode** [leibnitz27/cfr#169]
It would be nice if CFR was released more frequently, because it is pretty annoying when I have to use a 3 months old version from maven in my project when I know the latest version is already so much better.

**Comment by Marcono1234** [comment]
You can use https://jitpack.io/#leibnitz27/cfr to get builds for any commit, however official releases are more convenient of course.

**Comment by GraxCode** [comment]
Another good reason is that obfuscators may abuse bugs like #170.

**Comment by leibnitz27** [comment]
I massively slowed down the releases of CFR since opening it up on github (1/w -> 1/2m) given that I assumed people who were really interested would play with master. 

Fair enough, I hadn't really considered the maven dependency consumers.

Anyway, yes, it's been embarrassingly long since the last release, so 150 is now on maven central.

**Comment by leibnitz27** [comment]
(and will be on the website once I get a chance).
