### ISSUE TITLE
ClassFileSourceImpl NPE at line 371

### ISSUE THREAD

**Issue by ik666** [leibnitz27/cfr#279]
# CFR 0.153-SNAPSHOT

I get a NPE while decompiling some jar archives in ClassFileSourceImpl.java line 371.

FIX: 
add before :
if (file.getParentFile() !=)

**Comment by leibnitz27** [comment]
Thanks.  Do you have something specific you can share that can trigger it?
Would like to know how it got into that state.  (A file without a
directory?)

Are you driving this from command line or api?

**Comment by ik666** [comment]
Hi,

I did a 

`java -jar cfr-0.153-SNAPSHOT.jar  ...-8.0.jar` 

on the command line ...

> Am 15.12.2021 um 13:09 schrieb Lee Benfield ***@***.***>:
> 
> 
> Thanks. Do you have something specific you can share that can trigger it?
> Would like to know how it got into that state. (A file without a
> directory?)
> 
> Are you driving this from command line or api?
>

**Comment by leibnitz27** [comment]
What operating system?

**Comment by ik666** [comment]
I'm running MacOS 12.0 using openjdk version "15.0.1" 2020-10-20 ...

**Comment by Marcono1234** [comment]
This can be reproduced by creating a JAR file with a `MANIFEST.MF` file with a `Class-Path` attribute, and then running CFR only with the file name of the JAR.
For example:
1. Download [class-path-test.jar.txt](https://github.com/leibnitz27/cfr/files/7781324/class-path-test.jar.txt)
2. Remove the `.txt` extension
3. Run CFR:
    ```
    java -jar cfr-0.152.jar class-path-test.jar
   ```

Error:
```
Exception analysing jar
java.lang.NullPointerException: Cannot invoke "java.io.File.getCanonicalPath()" because the return value of "java.io.File.getParentFile()" is null
org.benf.cfr.reader.state.ClassFileSourceImpl.addToRelativeClassPath(ClassFileSourceImpl.java:371)
org.benf.cfr.reader.state.ClassFileSourceImpl.addJarContent(ClassFileSourceImpl.java:270)
org.benf.cfr.reader.state.DCCommonState.explicitlyLoadJar(DCCommonState.java:141)
org.benf.cfr.reader.Driver.doJar(Driver.java:127)
org.benf.cfr.reader.CfrDriverImpl.analyse(CfrDriverImpl.java:76)
org.benf.cfr.reader.Main.main(Main.java:54)
```

Because `class-path-test.jar` is a relative path, it does not have a parent, therefore `getParentFile()` returns `null`, as mentioned by @ik666 in the description.

Dependening on what the desired behavior is, it could be a solution to first call `getCanonicalFile()` before calling `getParentFile()`. Though adding a `null` check would be good either way.

**Comment by leibnitz27** [comment]
Excellent - thanks both (marcono, long time no speak ;) ).
