### ISSUE TITLE
Hide Eclipse enum switch table when --eclipse option is set

### ISSUE THREAD

**Issue by Marcono1234** [leibnitz27/cfr#28]
# CFR version
0.147

# Description
Eclipse compiles switch statements on enum values differently than `javac` (https://www.benf.org/other/cfr/switch-on-enum.html). Instead of adding an inner class, it adds the switch array (`$SWITCH_TABLE$mypackage$MyEnum`) as field and adds a method with the same name which lazily initializes the array and returns it.

Currently CFR outputs this even when using `--eclipse`:
```
public enum MyEnum {
    FIRST;

    private static /* synthetic */ int[] $SWITCH_TABLE$mypackage$MyEnum;

    public int get() {
        switch (MyEnum.$SWITCH_TABLE$mypackage$MyEnum()[this.ordinal()]) {
            case 1: {
                return 2;
            }
        }
        return -1;
    }

    static /* synthetic */ int[] $SWITCH_TABLE$mypackage$MyEnum() {
        if ($SWITCH_TABLE$mypackage$MyEnum != null) {
            int[] arrn;
            return arrn;
        }
        int[] arrn = new int[MyEnum.values().length];
        try {
            arrn[MyEnum.FIRST.ordinal()] = 1;
        }
        catch (NoSuchFieldError noSuchFieldError) {}
        $SWITCH_TABLE$mypackage$MyEnum = arrn;
        return arrn;
    }
}
```

# Reproduction steps
1. Compile the following code using Eclipse
    ```
    package mypackage;

    public enum MyEnum {
        FIRST;
        
        public int get() {
            switch (this) {
                case FIRST:
                    return 2;
                default:
                    return -1;
            }
        }
    }
    ```
2. Use CFR with the `--eclipse` option (enabled by default)

Alternatively, decompile the following `.jar` (remove `.zip` from its name, this was only added to make GitHub happy):
[enum-switch.jar.zip](https://github.com/leibnitz27/cfr/files/3756980/enum-switch.jar.zip)

**Comment by leibnitz27** [comment]
Hmm - this is interesting - ecj must have changed again - the switch code previously handled desugaring eclipse switches nicely.   

I confess, I don't test against ecj as much as I should, because, well, I don't like eclipse ;)

@Marcono1234 If you fancy adding ecj targets to cfr_tests, I would very much appreciate it.

**Comment by Marcono1234** [comment]
How should I add a test for this? Do you want me to add it under `hardcoded`?

Or are you planning to add profiles for ecj as well? It can be downloaded as standalone jar and apparently be used very similar to `javac`:
https://help.eclipse.org/2019-09/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Fguide%2Fjdt_int.htm
https://help.eclipse.org/2019-09/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Ftasks%2Ftask-using_batch_compiler.htm

I am also not quite sure whether I understood correctly how cfr_tests works. There are currently no automatic checks, are there? So you compile the source files, let CFR decompile them and then check whether the result is what you expected?

**Comment by leibnitz27** [comment]
Because there's a lot of environment dependent stuff, yes, the tests are non-automatic.  Also, having a seperate repository allows me to stop being anal about java6 usage ;)

https://github.com/leibnitz27/cfr_tests

Main page has (hopefully) sufficient instructions to generate tests, and to check them - i.e. you use a 'known good' cfr to generate your base case.    I definitely don't want to embed these in code, because 'known best' moves around a lot! :) 

I rerun the tests after pretty much every code change (At least java6 and java13).

If ecj dependency can be added such that compile.bat / compile.sh can compile with ecj, and we can test an ecj set, awesome!

**Comment by Marcono1234** [comment]
Alright, I might try tinkering a little bit with it during the next days and see if there is a way to use ecj as compiler as well.

**Comment by Marcono1234** [comment]
The code generated by ecj might change in the future because it appears that it is not thread-safe, see Eclipse bug report [544521](https://bugs.eclipse.org/bugs/show_bug.cgi?id=544521).

**Comment by leibnitz27** [comment]
Heh, yes, I noted that here http://www.benf.org/other/cfr/eclipse-differences.html

**Comment by leibnitz27** [comment]
Yep, they changed their switch generation style slightly.  Small pattern tweak.
