### ISSUE TITLE
Decompiling class named "aux.class" fails on Windows.

### ISSUE THREAD

**Issue by ghxstdev** [leibnitz27/cfr#66]
A problem is that in Windows, you cannot create a file named Aux for legacy reasons.
Some decompilers mitigate this issue by prefixing the `aux.class` with an uderscore like `_aux.class`, I'm wondering if there's a way to do this with CFR?

Output:
```
Exception analysing jar
Cannot create dumper org.benf.cfr.reader.util.output.Dumper$CannotCreate: java.io.FileNotFoundException: cfr_output\aux.java (The system cannot find the file specified)
org.benf.cfr.reader.util.output.FileDumper.<init>(FileDumper.java:57)
org.benf.cfr.reader.util.output.InternalDumperFactoryImpl.getNewTopLevelDumper(InternalDumperFactoryImpl.java:65)
org.benf.cfr.reader.Driver.doJarVersionTypes(Driver.java:248)
org.benf.cfr.reader.Driver.doJar(Driver.java:125)
org.benf.cfr.reader.CfrDriverImpl.analyse(CfrDriverImpl.java:65)
org.benf.cfr.reader.Main.main(Main.java:48)
```

**Comment by leibnitz27** [comment]
Hah, nice.

**Comment by leibnitz27** [comment]
(the same applies to 'con' and 'prn' btw)

**Comment by leibnitz27** [comment]
Linux

lee@lee-VirtualBox:~/tmp$ java -jar /tmp/cfr-0.149-SNAPSHOT.jar /tmp/baddos.jar --outputdir /tmp/baddos
Processing /tmp/baddos.jar (use silent to silence)
Processing foo.CON
Processing foo.auX
Processing foo.prn
Processing foo.con
Processing foo.aux
Processing foo.Aux

Windows

C:\code\cfr\target>java -jar cfr-0.149-SNAPSHOT.jar c:\temp\vmfiles\baddos.jar --outputdir c:\temp\baddos
Processing c:\temp\vmfiles\baddos.jar (use silent to silence)
Processing foo.CON_
Processing foo.auX_
Processing foo.prn_
Processing foo.con__0
Processing foo.aux__0
Processing foo.aux__1

**Comment by leibnitz27** [comment]
[baddos.jar.zip](https://github.com/leibnitz27/cfr/files/3949269/baddos.jar.zip)

(extra .zip for github happiness).

**Comment by Marcono1234** [comment]
There are more special file names on Windows. See https://en.wikipedia.org/wiki/Filename#Reserved_characters_and_words and there is also `CONIN$` and `CONOUT$`.

Here is a zip / jar with more invalid class names: 
[windows-filenames.jar.zip](https://github.com/leibnitz27/cfr/files/3957964/windows-filenames.jar.zip)

Warning: Don't try to unzip the file on Windows, you might have trouble removing some of the files. See this [serverfault answer](https://serverfault.com/a/96833) in cause you unzipped it by accident.

In theory [8.3 filenames](https://en.wikipedia.org/wiki/8.3_filename) could also cause issues since they would allow name collisions. And any of the above reserved file names is also invalid with leading or trailing white spaces (those are apparently not allowed on Windows anyways) and trailing dots, e.g. `CON        ....   `. However, these are not valid Java class names so there is probably no need to handle them.

**Comment by infahash** [comment]
This issue is partially fixed now. but when having folders named con,aux... it failed to create files inside that folder
![Screenshot_10](https://user-images.githubusercontent.com/14011796/77254159-6047f480-6c85-11ea-9ccb-aea54f095df8.png)
